manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ebastler
      url-base: https://github.com/ebastler
    - name: zhiayang
      url-base: https://github.com/zhiayang
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
  self:
    path: config
